/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${controllerPackage};

import ${packageName}.model.${entityName};
<#if withService>
import ${packageName}.service.${serviceName};
import lombok.RequiredArgsConstructor;
</#if>
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("${apiPrefix}/${entityNameLower}")
<#if withService>
@RequiredArgsConstructor
</#if>
public class ${controllerName} {
<#if withService>

    private final ${serviceName} service;

    @GetMapping
    public ResponseEntity<List<${entityName}>> getAll() {
        return ResponseEntity.ok(service.findAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<${entityName}> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<${entityName}> create(@RequestBody ${entityName} entity) {
        ${entityName} saved = service.save(entity);
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    @PutMapping("/{id}")
    public ResponseEntity<${entityName}> update(
            @PathVariable UUID id,
            @RequestBody ${entityName} entity) {
        return service.findById(id)
                .map(existing -> {
                    entity.setId(id);
                    return ResponseEntity.ok(service.save(entity));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (service.existsById(id)) {
            service.deleteById(id);
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
<#else>

    @GetMapping
    public ResponseEntity<List<${entityName}>> getAll() {
        // TODO: implement
        return ResponseEntity.ok().build();
    }

    @GetMapping("/{id}")
    public ResponseEntity<${entityName}> getById(@PathVariable UUID id) {
        // TODO: implement
        return ResponseEntity.ok().build();
    }

    @PostMapping
    public ResponseEntity<${entityName}> create(@RequestBody ${entityName} entity) {
        // TODO: implement
        return ResponseEntity.status(HttpStatus.CREATED).build();
    }

    @PutMapping("/{id}")
    public ResponseEntity<${entityName}> update(
            @PathVariable UUID id,
            @RequestBody ${entityName} entity) {
        // TODO: implement
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        // TODO: implement
        return ResponseEntity.noContent().build();
    }
</#if>
}
