/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageName}

import javax.persistence.*
import java.time.LocalDateTime
import java.util.UUID
<#list imports as import>
${import}
</#list>
<#if belongsTo?has_content || hasMany?has_content>
import java.util.ArrayList
</#if>

@Entity
@Table(name = "${tableName}")
class ${entityName}(
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    var id: UUID? = null,
<#list fields as field>
<#if field.name != "id">

    @Column(name = "${field.name}"<#if field.unique>, unique = true</#if><#if !field.nullable>, nullable = false</#if>)
    var ${field.name}: ${field.kotlinType}? = null,
</#if>
</#list>
<#list belongsTo![] as parent>

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "${parent?lower_case}_id")
    var ${parent?lower_case}: ${parent}? = null,
</#list>

    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: LocalDateTime? = null,

    @Column(name = "updated_at")
    var updatedAt: LocalDateTime? = null
) {
<#list hasMany![] as child>
    @OneToMany(mappedBy = "${entityNameLower}", cascade = [CascadeType.ALL], orphanRemoval = true)
    val ${child?lower_case}s: MutableList<${child}> = ArrayList()

</#list>
    @PrePersist
    protected fun onCreate() {
        createdAt = LocalDateTime.now()
        updatedAt = LocalDateTime.now()
    }

    @PreUpdate
    protected fun onUpdate() {
        updatedAt = LocalDateTime.now()
    }
}
