/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${testPackage}

import ${packageBase}.model.${entityName}
import ${packageBase}.repository.${repositoryName}
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager
import org.assertj.core.api.Assertions.*

@DataJpaTest
@DisplayName("${entityName} Integration Tests")
class ${entityName}IntegrationTest {

    @Autowired
    private lateinit var entityManager: TestEntityManager

    @Autowired
    private lateinit var repository: ${repositoryName}

    private lateinit var test${entityName}: ${entityName}

    @BeforeEach
    fun setUp() {
        test${entityName} = ${entityName}()
        // TODO: set required fields on test${entityName}
        entityManager.persistAndFlush(test${entityName})
    }

    @Test
    @DisplayName("Should persist and retrieve ${entityNameLower}")
    fun shouldPersistAndRetrieve() {
        val found = repository.findById(test${entityName}.id!!)
        assertThat(found).isPresent
    }

    @Test
    @DisplayName("Should find all ${entityNameLower}s")
    fun shouldFindAll() {
        assertThat(repository.findAll()).isNotEmpty
    }

    @Test
    @DisplayName("Should delete ${entityNameLower}")
    fun shouldDelete() {
        repository.deleteById(test${entityName}.id!!)
        assertThat(repository.findById(test${entityName}.id!!)).isEmpty
    }
}
