/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${testPackage};

import ${packageName}.model.${entityName};
import ${packageName}.repository.${repositoryName};
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

@DataJpaTest
@DisplayName("${entityName} Integration Tests")
class ${entityName}IntegrationTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private ${repositoryName} repository;

    private ${entityName} test${entityName};

    @BeforeEach
    void setUp() {
        test${entityName} = new ${entityName}();
        // TODO: set required fields on test${entityName}
        entityManager.persistAndFlush(test${entityName});
    }

    @Test
    @DisplayName("Should persist and retrieve ${entityNameLower}")
    void shouldPersistAndRetrieve() {
        Optional<${entityName}> found = repository.findById(test${entityName}.getId());
        assertThat(found).isPresent();
    }

    @Test
    @DisplayName("Should find all ${entityNameLower}s")
    void shouldFindAll() {
        assertThat(repository.findAll()).isNotEmpty();
    }

    @Test
    @DisplayName("Should delete ${entityNameLower}")
    void shouldDelete() {
        repository.deleteById(test${entityName}.getId());
        assertThat(repository.findById(test${entityName}.getId())).isEmpty();
    }
}
