/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.mapper

import ${packageBase}.model.${entityName}
import ${packageBase}.dto.${dtoName}
import org.mapstruct.Mapper
import org.mapstruct.MappingTarget
import org.mapstruct.ReportingPolicy

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
interface ${entityName}Mapper {

    fun toDTO(entity: ${entityName}): ${dtoName}

    fun toEntity(dto: ${dtoName}): ${entityName}

    fun updateEntity(dto: ${dtoName}, @MappingTarget entity: ${entityName})
}
