/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageName}.mapper;

import ${packageName}.model.${entityName};
import ${packageName}.dto.${dtoName};
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface ${entityName}Mapper {

    ${dtoName} toDTO(${entityName} entity);

    ${entityName} toEntity(${dtoName} dto);

    void updateEntity(${dtoName} dto, @MappingTarget ${entityName} entity);
}
