/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${repositoryPackage}

import ${packageName}.model.${entityName}
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import java.util.UUID

@Repository
interface ${repositoryName} : JpaRepository<${entityName}, UUID>
