/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.resolver

import ${packageBase}.model.${entityName}
import ${packageBase}.service.${serviceName}
import org.springframework.graphql.data.method.annotation.Argument
import org.springframework.graphql.data.method.annotation.MutationMapping
import org.springframework.graphql.data.method.annotation.QueryMapping
import org.springframework.stereotype.Controller
import java.util.Optional
import java.util.UUID

@Controller
class ${entityName}Resolver(private val service: ${serviceName}) {

    @QueryMapping
    fun ${entityNameLower}s(): List<${entityName}> = service.findAll()

    @QueryMapping
    fun ${entityNameLower}(@Argument id: UUID): Optional<${entityName}> = service.findById(id)

    @MutationMapping
    fun create${entityName}(@Argument input: ${entityName}): ${entityName} = service.save(input)

    @MutationMapping
    fun update${entityName}(@Argument id: UUID, @Argument input: ${entityName}): ${entityName} {
        input.id = id
        return service.save(input)
    }

    @MutationMapping
    fun delete${entityName}(@Argument id: UUID): Boolean {
        if (service.existsById(id)) {
            service.deleteById(id)
            return true
        }
        return false
    }
}
