/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.resolver;

import ${packageBase}.model.${entityName};
import ${packageBase}.service.${serviceName};
import lombok.RequiredArgsConstructor;
import org.springframework.graphql.data.method.annotation.Argument;
import org.springframework.graphql.data.method.annotation.MutationMapping;
import org.springframework.graphql.data.method.annotation.QueryMapping;
import org.springframework.stereotype.Controller;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Controller
@RequiredArgsConstructor
public class ${entityName}Resolver {

    private final ${serviceName} service;

    @QueryMapping
    public List<${entityName}> ${entityNameLower}s() {
        return service.findAll();
    }

    @QueryMapping
    public Optional<${entityName}> ${entityNameLower}(@Argument UUID id) {
        return service.findById(id);
    }

    @MutationMapping
    public ${entityName} create${entityName}(@Argument ${entityName} input) {
        return service.save(input);
    }

    @MutationMapping
    public ${entityName} update${entityName}(@Argument UUID id, @Argument ${entityName} input) {
        input.setId(id);
        return service.save(input);
    }

    @MutationMapping
    public boolean delete${entityName}(@Argument UUID id) {
        if (service.existsById(id)) {
            service.deleteById(id);
            return true;
        }
        return false;
    }
}
