/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${servicePackage}

import ${packageBase}.model.${entityName}
<#if withRepository>
import ${packageBase}.repository.${repositoryName}
</#if>
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.util.Optional
import java.util.UUID

@Service
@Transactional
<#if withRepository>
class ${serviceName}(private val repository: ${repositoryName}) {

    @Transactional(readOnly = true)
    fun findAll(): List<${entityName}> = repository.findAll()

    @Transactional(readOnly = true)
    fun findById(id: UUID): Optional<${entityName}> = repository.findById(id)

    fun save(entity: ${entityName}): ${entityName} = repository.save(entity)

    fun deleteById(id: UUID) = repository.deleteById(id)

    fun delete(entity: ${entityName}) = repository.delete(entity)

    @Transactional(readOnly = true)
    fun existsById(id: UUID): Boolean = repository.existsById(id)

    @Transactional(readOnly = true)
    fun count(): Long = repository.count()
}
<#else>
class ${serviceName} {

    fun findAll(): List<${entityName}> {
        // TODO: implement
        return emptyList()
    }

    fun findById(id: UUID): Optional<${entityName}> {
        // TODO: implement
        return Optional.empty()
    }

    fun save(entity: ${entityName}): ${entityName} {
        // TODO: implement
        return entity
    }

    fun deleteById(id: UUID) {
        // TODO: implement
    }

    fun existsById(id: UUID): Boolean {
        // TODO: implement
        return false
    }
}
</#if>
