/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${servicePackage};

import ${packageBase}.model.${entityName};
<#if withRepository>
import ${packageBase}.repository.${repositoryName};
import lombok.RequiredArgsConstructor;
</#if>
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
<#if withRepository>
@RequiredArgsConstructor
</#if>
@Transactional
public class ${serviceName} {
<#if withRepository>

    private final ${repositoryName} repository;

    @Transactional(readOnly = true)
    public List<${entityName}> findAll() {
        return repository.findAll();
    }

    @Transactional(readOnly = true)
    public Optional<${entityName}> findById(UUID id) {
        return repository.findById(id);
    }

    public ${entityName} save(${entityName} entity) {
        return repository.save(entity);
    }

    public void deleteById(UUID id) {
        repository.deleteById(id);
    }

    public void delete(${entityName} entity) {
        repository.delete(entity);
    }

    @Transactional(readOnly = true)
    public boolean existsById(UUID id) {
        return repository.existsById(id);
    }

    @Transactional(readOnly = true)
    public long count() {
        return repository.count();
    }
<#else>

    public List<${entityName}> findAll() {
        // TODO: implement
        return java.util.Collections.emptyList();
    }

    public Optional<${entityName}> findById(UUID id) {
        // TODO: implement
        return Optional.empty();
    }

    public ${entityName} save(${entityName} entity) {
        // TODO: implement
        return entity;
    }

    public void deleteById(UUID id) {
        // TODO: implement
    }

    public boolean existsById(UUID id) {
        // TODO: implement
        return false;
    }
</#if>
}
