/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.service;

import ${packageBase}.dto.AuthResponse;
import ${packageBase}.dto.LoginRequest;
import ${packageBase}.dto.RegisterRequest;
import ${packageBase}.model.${userEntity};
import ${packageBase}.repository.${userEntity}Repository;
import ${packageBase}.security.JwtUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class AuthService {

    private final ${userEntity}Repository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final AuthenticationManager authenticationManager;
    private final UserDetailsService userDetailsService;

    public AuthResponse register(RegisterRequest request) {
        ${userEntity} user = new ${userEntity}();
        user.set${usernameField?cap_first}(request.get${usernameField?cap_first}());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        if (request.getName() != null) {
            user.setName(request.getName());
        }
        userRepository.save(user);
        UserDetails userDetails = userDetailsService.loadUserByUsername(request.get${usernameField?cap_first}());
        return new AuthResponse(jwtUtil.generateToken(userDetails));
    }

    public AuthResponse login(LoginRequest request) {
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.get${usernameField?cap_first}(), request.getPassword())
        );
        UserDetails userDetails = userDetailsService.loadUserByUsername(request.get${usernameField?cap_first}());
        return new AuthResponse(jwtUtil.generateToken(userDetails));
    }
}
