/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.security;

import ${packageBase}.model.${userEntity};
import ${packageBase}.repository.${userEntity}Repository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class CustomUserDetailsService implements UserDetailsService {

    private final ${userEntity}Repository userRepository;

    @Override
    public UserDetails loadUserByUsername(String ${usernameField}) throws UsernameNotFoundException {
        ${userEntity} user = userRepository.findBy${usernameField?cap_first}(${usernameField})
                .orElseThrow(() -> new UsernameNotFoundException("User not found: " + ${usernameField}));

        return org.springframework.security.core.userdetails.User.builder()
                .username(user.get${usernameField?cap_first}())
                .password(user.getPassword())
                .authorities("ROLE_USER")
                .build();
    }
}
