/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.dto;

import lombok.Data;

@Data
public class LoginRequest {
    private String ${usernameField};
    private String password;
}
