/**
 * Generated by Spring Artisan
 * Author: ${author}
 */
package ${packageBase}.dto;

import lombok.Data;

@Data
public class RegisterRequest {
    private String ${usernameField};
    private String password;
    private String name;
}
